### ISSUE TITLE
Update format of the job get command

### ISSUE THREAD

**Issue by mharnish** [open-sce/fluent-cli#36]
Update the format of the `job get` command as described in the [wiki](https://github.com/open-sce/fluent-cli/wiki/Planned-3.0-CLI-Enhancements). The new format of the command, which only takes one required parameter and no optional parameters, should be: 
```bash
job get --jobId <Job ID>
```

**Comment by ctgao** [comment]
A few notes for the proposed fix:

The "sortOptions" parameter is set to false on this command because I wanted to display the "jobId" option at the top of the list of options, allowing the user to see it more readily. The order can only be changed if the "sortOptions" parameter is false.
The "order" parameter is -2 because default is -1 and the order of options is sorted in numerical order.
